# World of Warcraft Raid Assignment Tool Configuration
# Copy this file to config.toml and update with your specific values

# URL to the Google Sheets document (must be publicly accessible)
# Example: https://docs.google.com/spreadsheets/d/1234567890abcdef/edit#gid=0
spreadsheet_url = "https://docs.google.com/spreadsheets/d/YOUR_SHEET_ID_HERE/edit#gid=0"

# Raid name - must be one of: MC, BWL, AQ40, Naxx
raid_name = "MC"

# Name of the specific page/sheet within the spreadsheet
page_name = "MC Assignments"

# Optional: Output file name (defaults to <raid_name>_assignments.txt)
# output_file = "molten_core_assignments.txt"

# Optional: Additional configuration
[formatting]
# Include timestamps in output
include_timestamp = true

# Custom header text
custom_header = "Guild Raid Assignments"

# Examples for different raids:
#
# For Molten Core:
# raid_name = "MC"
# page_name = "MC Assignments"
#
# For Blackwing Lair:
# raid_name = "BWL"
# page_name = "BWL Assignments"
#
# For Ahn'Qiraj 40:
# raid_name = "AQ40"
# page_name = "AQ40 Assignments"
#
# For Naxxramas:
# raid_name = "Naxx"
# page_name = "Naxx Assignments"